name: 'dkc-kz-agg'

services:
  php-fpm:
    container_name: dkc-kz-agg-php
    build:
      context: ./local/php
      args:
        UID: ${UID}
        GID: ${GID}
    ports:
      - '9000:9000'
    volumes:
      - ../backend:/var/www/backend
      - ./local/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./local/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mongodb
    networks:
      - dkc_kz_net

  mongodb:
    container_name: dkc-kz-agg-mongo
    image: mongo:4.4
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - '27017:27017'
    volumes:
      - ./local/mongo/initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./local/mongo/data/db/:/data/db/
      - ./local/mongo/data/log/:/var/log/mongodb/
      - ./local/mongo/backup/:/backup/
    networks:
      - dkc_kz_net

  rabbit:
    container_name: dkc-kz-agg-rabbit
    image: rabbitmq:3.13-management
    environment:
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./local/rabbitmq/data/:/var/lib/rabbitmq/
      - ./local/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - dkc_kz_net

  nginx:
    container_name: dkc-kz-agg-nginx
    image: nginx
    ports:
      - '80:80'
    env_file: .env
    volumes:
      - ../backend:/var/www/backend
      - ./local/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./local/nginx/logs:/var/log/nginx/
    depends_on:
      - php-fpm
    networks:
      - dkc_kz_net


networks:
  dkc_kz_net:
    driver: bridge